# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :unit_tests do
  scan(
    package_path: ".",            # SPM projesi olduğu için ana dizin
    scheme: "ICTMDBHomeModule",   # Projenizin scheme adı
    device: "iPhone 16",          # Testin koşacağı simülatör
    output_directory: "fastlane/test_output",
    output_types: "junit,html"
  )
end
